### ISSUE TITLE
BucketHub: EvmError Revert

### ISSUE THREAD

**Issue by Ayodeji63** [bnb-chain/greenfield-contracts-sdk#32]
I'm currently working on deploying the `Ebook-shop` contract in the example of the greenfield-sdk. However, I encountered an error when attempting to create a series which is creating a Bucket. I've provided more info about the scripts below, and iam using Foundry for deployment.
![Screenshot from 2024-02-12 22-56-42](https://github.com/bnb-chain/greenfield-contracts-sdk/assets/75380773/0d68c7e1-1263-4c5c-bafb-3ecbdf23c2fa)

Below is the interaction script to create series

```javascript
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.18;
import {EbookStore} from "../src/Ebook.sol";
import {Script} from "forge-std/Script.sol";
import {console} from "forge-std/console.sol";
import {BucketStorage} from "@bnb-chain/greenfield-contracts/contracts/middle-layer/resource-mirror/storage/BucketStorage.sol";

contract CreateSeries is Script {
    address primaryAddress = 0x63d6fB13DeD20AEEf9e25cA264b5C1Bd2ca2bc22;
    address ebookAddress = 0x381B6BFd8e208F79d21C647Daf95247c669C55b9;
    string name = "ebookStore";
    uint64 chargedReadQuota = 0;
    address spAddress = primaryAddress;
    uint256 expireHeight = 	4959457;
    bytes sig = "0x";
    BucketStorage.BucketVisibilityType visibility = BucketStorage.BucketVisibilityType.PublicRead; // Use the local enum
    address public initOwner = vm.addr(vm.envUint("OP_PRIVATE_KEY"));
    function run() public {
        string memory messageToSign = "createSeries";
        uint256  _privateKey = vm.envUint("OP_PRIVATE_KEY");
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(_privateKey, keccak256(abi.encodePacked(messageToSign)));
        // Call the createSeries function with the signature
        vm.startBroadcast(initOwner);
        EbookStore(ebookAddress).createSeries{value: 0.01 ether}(name, visibility, chargedReadQuota, spAddress, expireHeight, bytes(abi.encodePacked(v, r, s)));
        vm.stopBroadcast();
    }


}


```

Contract Address: 0x381B6BFd8e208F79d21C647Daf95247c669C55b9

**Comment by STdevK** [comment]
Can you share the information in `package.json`?

**Comment by Ayodeji63** [comment]
This is the information in `package.json`
```javascript
{
  "name": "greenfield-contracts-sdk",
  "version": "1.0.0",
  "description": "Smart Contract library for Greenfield",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/bnb-chain/greenfield-contracts-sdk.git"
  },
  "author": "BNB Chain",
  "license": "GNU Affero General Public License v3.0",
  "bugs": {
    "url": "https://github.com/bnb-chain/greenfield-contracts-sdk/issues"
  },
  "homepage": "https://github.com/bnb-chain/greenfield-contracts-sdk#readme",
  "publishConfig": {
    "registry": "https://registry.npmjs.org/",
    "access": "public"
  },
  "dependencies": {
    "@bnb-chain/greenfield-contracts": "1.0.0",
    "@bnb-chain/greenfield-contracts-sdk": "1.0.0",
    "@openzeppelin/contracts": "^4.9.3",
    "@openzeppelin/contracts-upgradeable": "^4.9.3"
  }
}

```

**Comment by Pythonberg1997** [comment]
Please try the latest version v1.1.0

**Comment by deepcrazy** [comment]
Can you share your updated `package.json` again? Also, do share your interaction script to create series (if you've updated anything in it).

**Comment by Ayodeji63** [comment]
I was able to resolve the error, all i did was to grant the `EbookShop` contract a role.

```javascript
contract GrantRole is Script {
    address public constant BUCKET_HUB_EB = 0x5BB17A87D03620b313C39C24029C94cB5714814A;
     address public initOwner = vm.addr(vm.envUint("OP_PRIVATE_KEY"));
     bytes32 ROLE_CREATE = 0xa7a925e56b0f4627a3e4910a6e10d23a82143f84f9d73d587c9ef425941ace8e;

     function run() external {
        address mostRecentlyDeployed = DevOpsTools.get_most_recent_deployment(
            "EbookShop",
            block.chainid
        );
        console.log(mostRecentlyDeployed);
        grantRole(mostRecentlyDeployed);
    }
    function grantRole(address contractAddress) public {
        vm.startBroadcast(initOwner);
        GnfdAccessControl(BUCKET_HUB_EB).grantRole(ROLE_CREATE, contractAddress, uint256(block.number * 100));
        vm.stopBroadcast();
    }
}

```

I'm facing a challenge after creating a series. I haven't obtained a `tokenId` to represent the `ebookId`, nor have I gottne a callback function, specifically the `greenfieldCall`. This callback function is expected to be triggered by the `BUCKET_HUB contract.`

Below is the log when i run `createSeries`
![Screenshot from 2024-02-15 22-49-27](https://github.com/bnb-chain/greenfield-contracts-sdk/assets/75380773/849e7264-682b-43fb-80b1-c8b2f2bf554a)

**Comment by Pythonberg1997** [comment]
The `greenfieldCall` function in the `Ebook-shop` contract is virtual and non-implemented. For example, in your case, you're creating a bucket, so you need to implement this function(`function _createBucketCallback(uint32 _status, uint256 _tokenId, bytes memory _callbackData) internal virtual {}`).

**Comment by Pythonberg1997** [comment]
The `tokenID` and other info will be passed as input to the function `greenfieldCall`. And the dApp could do some thing with these data, for example, writing `tokenID` to a global variable `map(address => uint256[])` and emitting events. Then the user could query. `Ebook-shop` has not implemented this part of the function, so it is not possible to directly query the `tokenID`. However, you can still query it in the events of the system contract. There will be a `CreateSuccess(creator, id)` in the `BucketHub` contract.

**Comment by Ayodeji63** [comment]
Okay. Thanks @Pythonberg1997. i just found out, i can't create `object` from BSC, was wondering where the `objectTokenId` will come from. i guess i will have create bucket on `BSC` then create `object` on `greenField`.
Is there a better convention for this?

**Comment by Pythonberg1997** [comment]
No..at the moment. @Ayodeji63
