### ISSUE TITLE
Can't create bucket

### ISSUE THREAD

**Issue by AndrewChupin** [bnb-chain/greenfield-contracts-sdk#34]
Smart-contract address - `0x2334daA994C33150F535fbf16AcAF759Ce5652CF`
Trying to call - `createDevAccount`

`name`=open-store-bsc1
`spAddress`=0x03A42215dC678E65A145B3E18e84046a959DC11F
`height`=5288718
`approveSign`=0x7b226275636b65745f6e616d65223a226f70656e2d73746f72652d62736331222c22636861726765645f726561645f71756f7461223a2230222c2263726561746f72223a22307832353541363265393565396341463431364463376630373141384539654334324362353362433532222c227061796d656e745f61646472657373223a22307832353541363265393565396341463431364463376630373141384539654334324362353362433532222c227072696d6172795f73705f61646472657373223a22307830334134323231356443363738453635413134354233453138653834303436613935394443313146222c227072696d6172795f73705f617070726f76616c223a7b22657870697265645f686569676874223a2235323738383138222c22676c6f62616c5f7669727475616c5f67726f75705f66616d696c795f6964223a342c22736967223a22496d54702b4968337172413651566f436179503933504d6a4d4159712b646b75726f35746774797165564d4f6432515467523762772f3638557a706f302f7a3159626169526a31567a5047324e746d457567744f7651413d227d2c227669736962696c697479223a225649534942494c4954595f545950455f5055424c49435f52454144227d

![telegram-cloud-photo-size-2-5361705184142678607-y](https://github.com/bnb-chain/greenfield-contracts-sdk/assets/15245196/50979352-bdf8-4cee-8336-66f36db5f7a6)
![telegram-cloud-photo-size-2-5361705184142678608-y](https://github.com/bnb-chain/greenfield-contracts-sdk/assets/15245196/b2e01820-4e06-4013-bf96-482010127447)
![telegram-cloud-photo-size-2-5361705184142678613-y](https://github.com/bnb-chain/greenfield-contracts-sdk/assets/15245196/73457607-b25e-4f55-89c4-e4171222f782)
![telegram-cloud-photo-size-2-5361705184142678804-y](https://github.com/bnb-chain/greenfield-contracts-sdk/assets/15245196/ef7fda42-39a4-4660-8fd8-82075a96645a)

**Comment by Pythonberg1997** [comment]
It's mainnet or testnet?

**Comment by AndrewChupin** [comment]
testnet

**Comment by Pythonberg1997** [comment]
Try to simulate your transaction to get an error msg returned. Or we don't know what really happened.

**Comment by anchupin** [comment]
@pythonberg1997 Hey, I see that you had new version in sdks.

Could you please add example how to call `createSeries` in https://github.com/bnb-chain/greenfield-contracts-sdk/blob/main/contracts/examples/ebook-shop.sol
